/**
 * ARCHIVO GENERADO — no editar a mano.
 * Fuente: src/data/seed.js  ·  Regenerar con: npm run seed:gs
 *
 * Datos de ejemplo. Se cargan con la función seedDemoData() (menú "FET Seguimiento")
 * y solo si la hoja "Actividades" está vacía. Este archivo es opcional.
 */
const SEED_ = {
  "activities": [
    {
      "id": 1,
      "periodo": "2026-2",
      "numero": 1,
      "nombre": "Preparación de sílabos por asignatura",
      "tipo": "Académica",
      "linea": "Docencia",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-01",
      "fecha_fin": "2026-08-10",
      "avance": 100,
      "estado": "Completada",
      "observaciones": "Sílabos cargados en el campus.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 2,
      "periodo": "2026-2",
      "numero": 2,
      "nombre": "Inducción a estudiantes",
      "tipo": "Académica",
      "linea": "Docencia",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-03",
      "fecha_fin": "2026-08-08",
      "avance": 100,
      "estado": "Completada",
      "observaciones": "Realizada con éxito.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 3,
      "periodo": "2026-2",
      "numero": 3,
      "nombre": "Desarrollo de clases (Periodo 1)",
      "tipo": "Académica",
      "linea": "Docencia",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-10",
      "fecha_fin": "2026-09-26",
      "avance": 70,
      "estado": "En desarrollo",
      "observaciones": "Clases desarrolladas según cronograma.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 4,
      "periodo": "2026-2",
      "numero": 4,
      "nombre": "Aplicación de evaluación parcial 1",
      "tipo": "Académica",
      "linea": "Docencia",
      "responsable": "Docente",
      "fecha_inicio": "2026-09-28",
      "fecha_fin": "2026-09-30",
      "avance": 0,
      "estado": "Pendiente",
      "observaciones": "Programada.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 5,
      "periodo": "2026-2",
      "numero": 5,
      "nombre": "Revisión de anteproyectos de grado",
      "tipo": "Investigación",
      "linea": "Investigación",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-15",
      "fecha_fin": "2026-08-30",
      "avance": 50,
      "estado": "En desarrollo",
      "observaciones": "En revisión de documentos.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 6,
      "periodo": "2026-2",
      "numero": 6,
      "nombre": "Entrega de sílabos",
      "tipo": "Académica",
      "linea": "Docencia",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-20",
      "fecha_fin": "2026-08-25",
      "avance": 100,
      "estado": "Completada",
      "observaciones": "Enviados a dirección de programa.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 7,
      "periodo": "2026-2",
      "numero": 7,
      "nombre": "Revisión de anteproyectos",
      "tipo": "Investigación",
      "linea": "Investigación",
      "responsable": "Docente",
      "fecha_inicio": "2026-08-25",
      "fecha_fin": "2026-08-30",
      "avance": 100,
      "estado": "Completada",
      "observaciones": "Dictámenes emitidos.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 8,
      "periodo": "2026-2",
      "numero": 8,
      "nombre": "Informe parcial de actividades",
      "tipo": "Administrativa",
      "linea": "Gestión académica",
      "responsable": "Docente",
      "fecha_inicio": "2026-09-01",
      "fecha_fin": "2026-09-05",
      "avance": 0,
      "estado": "Pendiente",
      "observaciones": "Preparación de borrador.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 9,
      "periodo": "2026-2",
      "numero": 9,
      "nombre": "Capacitación docente en pedagogía",
      "tipo": "Capacitación",
      "linea": "Desarrollo profesoral",
      "responsable": "Coordinación",
      "fecha_inicio": "2026-09-10",
      "fecha_fin": "2026-09-12",
      "avance": 80,
      "estado": "En desarrollo",
      "observaciones": "Asistencia activa.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    },
    {
      "id": 10,
      "periodo": "2026-2",
      "numero": 10,
      "nombre": "Cierre de actividades y entregas finales",
      "tipo": "Administrativa",
      "linea": "Gestión académica",
      "responsable": "Docente",
      "fecha_inicio": "2026-12-01",
      "fecha_fin": "2026-12-10",
      "avance": 0,
      "estado": "Programada",
      "observaciones": "Por ejecutar al final del periodo.",
      "creado": "2026-08-01T08:00:00",
      "actualizado": "2026-08-01T08:00:00"
    }
  ],
  "reports": [
    {
      "id": 1,
      "actividad_id": 1,
      "fecha_reporte": "2026-08-10",
      "avance_realizado": "Sílabos cargados en el campus virtual para todas las asignaturas asignadas.",
      "dificultades": "Sin novedades relevantes.",
      "resultados": "100% de la planificación del microcurrículo completada.",
      "acciones_siguientes": "Iniciar la impartición de clases.",
      "porcentaje": 100,
      "estado": "Completada",
      "proxima_revision": "",
      "autor": "Docente",
      "creado": "2026-08-10T09:00:00"
    },
    {
      "id": 2,
      "actividad_id": 2,
      "fecha_reporte": "2026-08-08",
      "avance_realizado": "Jornada de inducción desarrollada satisfactoriamente con asistencia completa.",
      "dificultades": "Aforo limitado en el aula principal.",
      "resultados": "Estudiantes orientados sobre el reglamento y sílabos.",
      "acciones_siguientes": "Monitorear adaptación inicial.",
      "porcentaje": 100,
      "estado": "Completada",
      "proxima_revision": "2026-08-15",
      "autor": "Docente",
      "creado": "2026-08-08T09:00:00"
    },
    {
      "id": 3,
      "actividad_id": 3,
      "fecha_reporte": "2026-08-31",
      "avance_realizado": "Avance temático del 35% cumplido según lo planificado.",
      "dificultades": "Ajuste de horarios por actividades extracurriculares.",
      "resultados": "Buen nivel de asistencia.",
      "acciones_siguientes": "Continuar con las unidades 3 y 4.",
      "porcentaje": 35,
      "estado": "En desarrollo",
      "proxima_revision": "2026-09-15",
      "autor": "Docente",
      "creado": "2026-08-31T09:00:00"
    },
    {
      "id": 4,
      "actividad_id": 3,
      "fecha_reporte": "2026-09-18",
      "avance_realizado": "Avance temático del 70% cumplido según lo planificado.",
      "dificultades": "Ajuste de horarios por actividades extracurriculares.",
      "resultados": "Buen nivel de asistencia y participación estudiantil.",
      "acciones_siguientes": "Preparación de evaluaciones parciales.",
      "porcentaje": 70,
      "estado": "En desarrollo",
      "proxima_revision": "2026-09-28",
      "autor": "Docente",
      "creado": "2026-09-18T09:00:00"
    },
    {
      "id": 5,
      "actividad_id": 5,
      "fecha_reporte": "2026-08-22",
      "avance_realizado": "25% de las propuestas revisadas.",
      "dificultades": "Retrasos menores en entrega por parte de estudiantes.",
      "resultados": "Primeras retroalimentaciones enviadas.",
      "acciones_siguientes": "Continuar con la primera tanda.",
      "porcentaje": 25,
      "estado": "En desarrollo",
      "proxima_revision": "2026-08-28",
      "autor": "Docente",
      "creado": "2026-08-22T09:00:00"
    },
    {
      "id": 6,
      "actividad_id": 5,
      "fecha_reporte": "2026-08-30",
      "avance_realizado": "50% de las propuestas revisadas con correcciones devueltas.",
      "dificultades": "Retrasos menores en entrega por parte de estudiantes.",
      "resultados": "Retroalimentaciones enviadas a los grupos.",
      "acciones_siguientes": "Completar la revisión de la segunda tanda.",
      "porcentaje": 50,
      "estado": "En desarrollo",
      "proxima_revision": "2026-09-10",
      "autor": "Docente",
      "creado": "2026-08-30T09:00:00"
    },
    {
      "id": 7,
      "actividad_id": 6,
      "fecha_reporte": "2026-08-25",
      "avance_realizado": "Entrega formal completada a la jefatura académica.",
      "dificultades": "Ninguna.",
      "resultados": "Aprobación recibida.",
      "acciones_siguientes": "Seguimiento periódico.",
      "porcentaje": 100,
      "estado": "Completada",
      "proxima_revision": "2026-09-01",
      "autor": "Docente",
      "creado": "2026-08-25T09:00:00"
    },
    {
      "id": 8,
      "actividad_id": 7,
      "fecha_reporte": "2026-08-30",
      "avance_realizado": "Evaluación formal de anteproyectos terminada.",
      "dificultades": "Ninguna.",
      "resultados": "Proyectos viables aprobados.",
      "acciones_siguientes": "Asignación de tutores.",
      "porcentaje": 100,
      "estado": "Completada",
      "proxima_revision": "2026-09-05",
      "autor": "Docente",
      "creado": "2026-08-30T09:00:00"
    },
    {
      "id": 9,
      "actividad_id": 9,
      "fecha_reporte": "2026-09-11",
      "avance_realizado": "Asistencia a 2 de los 5 módulos programados.",
      "dificultades": "Coordinación con horarios lectivos.",
      "resultados": "Constancia de asistencia parcial.",
      "acciones_siguientes": "Asistir a los módulos restantes.",
      "porcentaje": 40,
      "estado": "En desarrollo",
      "proxima_revision": "2026-09-12",
      "autor": "Docente",
      "creado": "2026-09-11T09:00:00"
    },
    {
      "id": 10,
      "actividad_id": 9,
      "fecha_reporte": "2026-09-12",
      "avance_realizado": "Asistencia a 4 de los 5 módulos programados.",
      "dificultades": "Coordinación con horarios lectivos.",
      "resultados": "Certificación parcial obtenida.",
      "acciones_siguientes": "Completar el último módulo evaluativo.",
      "porcentaje": 80,
      "estado": "En desarrollo",
      "proxima_revision": "2026-09-15",
      "autor": "Docente",
      "creado": "2026-09-12T09:00:00"
    }
  ]
};
